app:
  kafka:
    topics:
      orders: amazon.env.order-management.orders.pub
      payments: amazon.env.order-management.payments.pub
spring:
  application:
    name: service_b
  datasource:
    url: jdbc:postgresql://localhost:5433/service_b_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: paymentCompleted:com.amazon.service_b.payment.infrastructure.messaging.dto.PaymentCompletedEvent
    consumer:
      group-id: payment-processor
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.amazon.service_b.payment.infrastructure.messaging.dto
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.amazon.service_b.payment.infrastructure.messaging.dto.OrderCreatedEvent
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: validate
  web:
    error:
      include-stacktrace: never
